name: getting-started-tutorial
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nuvigator: ^0.2.2

dev_dependencies:
  build_runner: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
